In [1]:
import pandas as pd

In [2]:
#the data is from the google play store and you can find out the info for the applications
data=pd.read_csv("https://raw.githubusercontent.com/sunnysavita10/Statistics-With-Python-CompleteGuide/refs/heads/main/googleplaystore.csv")

In [3]:
data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

EDA

Data--clean

first will clean the data

create a profile of the data

clean my data

1. we create general profile of the data
2. statistics based analysis on top of the data
3. graph based analysis and you can make a conclusion from the data

In [4]:
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [5]:
data.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [6]:
data.shape

(10841, 13)

In [7]:
data.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

In [8]:
data.tail(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [9]:
data["Rating"]

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

In [10]:
data["Reviews"]

0           159
1           967
2         87510
3        215644
4           967
          ...
10836        38
10837         4
10838         3
10839       114
10840    398307
Name: Reviews, Length: 10841, dtype: object

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [12]:
data.sample()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
5799,Axxess AX-DSP,TOOLS,3.5,17,7.4M,"5,000+",Free,0,Everyone,Tools,"June 4, 2018",3_1,4.4 and up

In [13]:
data.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
6835,BU HANGİ ŞARKI ? - 2018,GAME,NaN,4,28M,100+,Free,0,Everyone,Trivia,"June 2, 2018",3.1.7z,4.0.3 and up
590,"Hide App, Private Dating, Safe Chat - PrivacyH...",DATING,4.4,35205,7.2M,"1,000,000+",Free,0,Everyone,Dating,"May 21, 2018",2.9.6,4.0 and up
5221,Age of AI: War Strategy,FAMILY,4.6,71,5.7M,500+,Paid,$2.49,Everyone,Strategy,"March 14, 2018",1.8,4.0 and up
8829,DS-L4 Viewer,PHOTOGRAPHY,3.5,13,7.9M,"1,000+",Free,0,Everyone,Photography,"January 29, 2018",1.2.0.9,5.0 and up
3975,Hay Day,FAMILY,4.5,10053186,94M,"100,000,000+",Free,0,Everyone,Casual,"June 28, 2018",1_39_93,4.0.3 and up
8429,Avenger Legends,FAMILY,4.0,3715,94M,"100,000+",Free,0,Everyone,Role Playing,"July 13, 2017",1.13.299,4.0.3 and up
6416,Lust in Terror Manor - The Truth Unveiled | Otome,GAME,4.1,355,53M,"10,000+",Free,0,Teen,Adventure,"July 10, 2018",1.0.6,4.1 and up
7840,Helper for CS:GO,TOOLS,4.4,208,6.0M,"10,000+",Free,0,Everyone,Tools,"June 16, 2016",1.2.1,4.1 and up
620,Ost. Zombies Cast - New Music and Lyrics,DATING,NaN,1,4.6M,100+,Free,0,Teen,Dating,"July 20, 2018",1.0,4.0.3 and up
9400,RUN JUMP RUN-fun games for free,GAME,4.4,661,42M,"100,000+",Free,0,Everyone,Action,"April 20, 2018",1.5.2,3.0 and up

# "data.describe() tells you the basic math summary for each numeric column — like how many values there are, the average, the lowest and highest values, and how spread out the data is."

In [14]:
data.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [15]:
data.describe(include="all")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,NaN,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,NaN,596,1695,1579,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [17]:
data["rating"].dtype

KeyError: 'rating'

In [ ]:
data.columns

In [ ]:
data["App"]

In [ ]:
len(data["App"].unique())

In [ ]:
data[data.duplicated()]   #to check duplicacy

1. i have to remove duplicate row

2. i can convert my rating columns data type into int

3. we have to correct size columns as well
   
4. correct the install column as well
   
5. correct the price column as well

6. rectify the data columns as well

In [18]:
data["Size"]      #its not correct

0                       19M
1                       14M
2                      8.7M
3                       25M
4                      2.8M
                ...
10836                   53M
10837                  3.6M
10838                  9.5M
10839    Varies with device
10840                   19M
Name: Size, Length: 10841, dtype: object

1mb=1024kb

19*1024kb

In [19]:
(data["Size"].unique())

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '1,000+',
       '470k', '226k', '240k', '89k', '234k', '257k', '861k', '467k',
       '157k', '44k', '676k', '67k', '552k', '885k', '1020k', '582k',
       '619k'], dtype=object)

In [20]:
data["Installs"]  #its not correct so we have to clean this data too

0            10,000+
1           500,000+
2         5,000,000+
3        50,000,000+
4           100,000+
            ...
10836         5,000+
10837           100+
10838         1,000+
10839         1,000+
10840    10,000,000+
Name: Installs, Length: 10841, dtype: object

In [21]:
data["Type"].value_counts()

Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64

In [22]:
#meaning of the 0 in the above output
data[data["Type"]=="0"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [23]:
data[data["Type"]=="Paid"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
234,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,$4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,$4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
290,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,$4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
291,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,$4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
427,Puffin Browser Pro,COMMUNICATION,4.0,18247,Varies with device,"100,000+",Paid,$3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10735,FP VoiceBot,FAMILY,NaN,17,157k,100+,Paid,$0.99,Mature 17+,Entertainment,"November 25, 2015",1.2,2.1 and up
10760,Fast Tract Diet,HEALTH_AND_FITNESS,4.4,35,2.4M,"1,000+",Paid,$7.99,Everyone,Health & Fitness,"August 8, 2018",1.9.3,4.2 and up
10782,Trine 2: Complete Story,GAME,3.8,252,11M,"10,000+",Paid,$16.99,Teen,Action,"February 27, 2015",2.22,5.0 and up
10785,"sugar, sugar",FAMILY,4.2,1405,9.5M,"10,000+",Paid,$1.20,Everyone,Puzzle,"June 5, 2018",2.7,2.3 and up
10798,Word Search Tab 1 FR,FAMILY,NaN,0,1020k,50+,Paid,$1.04,Everyone,Puzzle,"February 6, 2012",1.1,3.0 and up

In [24]:
data["Price"].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', 'Everyone', '$1.20', '$1.04'], dtype=object)

In [25]:
data["Content Rating"]

0          Everyone
1          Everyone
2          Everyone
3              Teen
4          Everyone
            ...
10836      Everyone
10837      Everyone
10838      Everyone
10839    Mature 17+
10840      Everyone
Name: Content Rating, Length: 10841, dtype: object

In [26]:
data["Content Rating"].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated', nan], dtype=object)

In [27]:
data["Genres"].unique()    #categorical data

array(['Art & Design', 'Art & Design;Pretend Play',
       'Art & Design;Creativity', 'Art & Design;Action & Adventure',
       'Auto & Vehicles', 'Beauty', 'Books & Reference', 'Business',
       'Comics', 'Comics;Creativity', 'Communication', 'Dating',
       'Education;Education', 'Education', 'Education;Creativity',
       'Education;Music & Video', 'Education;Action & Adventure',
       'Education;Pretend Play', 'Education;Brain Games', 'Entertainment',
       'Entertainment;Music & Video', 'Entertainment;Brain Games',
       'Entertainment;Creativity', 'Events', 'Finance', 'Food & Drink',
       'Health & Fitness', 'House & Home', 'Libraries & Demo',
       'Lifestyle', 'Lifestyle;Pretend Play',
       'Adventure;Action & Adventure', 'Arcade', 'Casual', 'Card',
       'Casual;Pretend Play', 'Action', 'Strategy', 'Puzzle', 'Sports',
       'Music', 'Word', 'Racing', 'Casual;Creativity',
       'Casual;Action & Adventure', 'Simulation', 'Adventure', 'Board',
       'Trivia', 'Role Playing', 'Simulation;Education',
       'Action;Action & Adventure', 'Casual;Brain Games',
       'Simulation;Action & Adventure', 'Educational;Creativity',
       'Puzzle;Brain Games', 'Educational;Education', 'Card;Brain Games',
       'Educational;Brain Games', 'Educational;Pretend Play',
       'Entertainment;Education', 'Casual;Education',
       'Music;Music & Video', 'Racing;Action & Adventure',
       'Arcade;Pretend Play', 'Role Playing;Action & Adventure',
       'Simulation;Pretend Play', 'Puzzle;Creativity',
       'Sports;Action & Adventure', 'Educational;Action & Adventure',
       'Arcade;Action & Adventure', 'Entertainment;Action & Adventure',
       'Puzzle;Action & Adventure', 'Strategy;Action & Adventure',
       'Music & Audio;Music & Video', 'Health & Fitness;Education',
       'Adventure;Education', 'Board;Brain Games',
       'Board;Action & Adventure', 'Board;Pretend Play',
       'Casual;Music & Video', 'Role Playing;Pretend Play',
       'Entertainment;Pretend Play', 'Video Players & Editors;Creativity',
       'Card;Action & Adventure', 'Medical', 'Social', 'Shopping',
       'Photography', 'Travel & Local',
       'Travel & Local;Action & Adventure', 'Tools', 'Tools;Education',
       'Personalization', 'Productivity', 'Parenting',
       'Parenting;Music & Video', 'Parenting;Education',
       'Parenting;Brain Games', 'Weather', 'Video Players & Editors',
       'Video Players & Editors;Music & Video', 'News & Magazines',
       'Maps & Navigation', 'Health & Fitness;Action & Adventure',
       'Educational', 'Casino', 'Adventure;Brain Games',
       'Trivia;Education', 'Lifestyle;Education',
       'Books & Reference;Creativity', 'Books & Reference;Education',
       'Puzzle;Education', 'Role Playing;Education',
       'Role Playing;Brain Games', 'Strategy;Education',
       'Racing;Pretend Play', 'Communication;Creativity',
       'February 11, 2018', 'Strategy;Creativity'], dtype=object)

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [29]:
data[["Last Updated","Current Ver","Android Ver"]]

           Last Updated         Current Ver         Android Ver
0       January 7, 2018               1.0.0        4.0.3 and up
1      January 15, 2018               2.0.0        4.0.3 and up
2        August 1, 2018               1.2.4        4.0.3 and up
3          June 8, 2018  Varies with device          4.2 and up
4         June 20, 2018                 1.1          4.4 and up
...                 ...                 ...                 ...
10836     July 25, 2017                1.48          4.1 and up
10837      July 6, 2018                 1.0          4.1 and up
10838  January 20, 2017                 1.0          2.2 and up
10839  January 19, 2015  Varies with device  Varies with device
10840     July 25, 2018  Varies with device  Varies with device

[10841 rows x 3 columns]

EDA 
1. collect the data 
2. by seeing the data or by creating a profile of the data will make some
observation if it will be required then will clean the data

1.i have to remove duplicate row
2.i can convert my reviews columns data type into int
3. we have to correct size columns as well
4. correct the install column as well
5. correct the price column as well
6. rectify the data columns as well

In [31]:
data=data.drop_duplicates()

In [32]:
data.head(1)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up

In [33]:
data[data.duplicated()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [34]:
data.drop_duplicates()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [35]:
data.shape

(10358, 13)

In [36]:
10841-10358    #duplicate data is 483

483

In [37]:
data["Rating"].dtype

dtype('float64')

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  object
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  object
 6   Type            10357 non-null  object
 7   Price           10358 non-null  object
 8   Content Rating  10357 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  object
 11  Current Ver     10350 non-null  object
 12  Android Ver     10355 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [39]:
data["Reviews"].dtype

dtype('O')

In [40]:
data["Reviews"].head(10)

0       159
1       967
2     87510
3    215644
4       967
5       167
6       178
7     36815
8     13791
9       121
Name: Reviews, dtype: object

In [41]:
data["Reviews"].shape

(10358,)

In [42]:
data.Reviews.str

In [43]:
data["Reviews"][0]

'159'

In [44]:
type(data["Reviews"][0])

str

In [45]:
data.Reviews.str.isnumeric()

0        True
1        True
2        True
3        True
4        True
         ...
10836    True
10837    True
10838    True
10839    True
10840    True
Name: Reviews, Length: 10358, dtype: bool

In [46]:
data[data.Reviews.str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [47]:
data[~data.Reviews.str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [48]:
~data.Reviews.str.isnumeric()

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Reviews, Length: 10358, dtype: bool

In [49]:
data_copy=data.copy()

In [50]:
data_copy

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [51]:
data.shape

(10358, 13)

In [52]:
data_copy.drop(data_copy[~data_copy.Reviews.str.isnumeric()].index)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [53]:
data_copy["Reviews"]=="3.0M"

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Reviews, Length: 10358, dtype: bool

In [54]:
data_copy=data.copy()

In [55]:
data[~data.Reviews.str.isnumeric()].index

Index([10472], dtype='int64')

In [56]:
data_copy[~data_copy.Reviews.str.isnumeric()].index

Index([10472], dtype='int64')

In [57]:
index_to_drop = data_copy[~data_copy.Reviews.str.isnumeric()].index
data_copy = data_copy.drop(index_to_drop)

In [58]:
index_to_drop

Index([10472], dtype='int64')

In [59]:
data_copy.shape

(10357, 13)

In [60]:
data_copy

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [61]:
~data_copy.Reviews.str.isnumeric()

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Reviews, Length: 10357, dtype: bool

In [62]:
data_copy[~data_copy.Reviews.str.isnumeric()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [63]:
#change data type
data_copy["Reviews"]=data_copy["Reviews"].astype("int")

In [64]:
data_copy["Reviews"].dtype    #converted into integer data type

dtype('int64')

In [65]:
data_copy["Reviews"][0]

np.int64(159)

In [66]:
data["Price"].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', 'Everyone', '$1.20', '$1.04'], dtype=object)

In [67]:
data["Price"].str.replace("$","").unique()

array(['0', '4.99', '3.99', '6.99', '1.49', '2.99', '7.99', '5.99',
       '3.49', '1.99', '9.99', '7.49', '0.99', '9.00', '5.49', '10.00',
       '24.99', '11.99', '79.99', '16.99', '14.99', '1.00', '29.99',
       '12.99', '2.49', '10.99', '1.50', '19.99', '15.99', '33.99',
       '74.99', '39.99', '3.95', '4.49', '1.70', '8.99', '2.00', '3.88',
       '25.99', '399.99', '17.99', '400.00', '3.02', '1.76', '4.84',
       '4.77', '1.61', '2.50', '1.59', '6.49', '1.29', '5.00', '13.99',
       '299.99', '379.99', '37.99', '18.99', '389.99', '19.90', '8.49',
       '1.75', '14.00', '4.85', '46.99', '109.99', '154.99', '3.08',
       '2.59', '4.80', '1.96', '19.40', '3.90', '4.59', '15.46', '3.04',
       '4.29', '2.60', '3.28', '4.60', '28.99', '2.95', '2.90', '1.97',
       '200.00', '89.99', '2.56', '30.99', '3.61', '394.99', '1.26',
       'Everyone', '1.20', '1.04'], dtype=object)

1. i have to remove duplicate row

2. i can convert my reviews columns data type into int

3. we have to correct size columns as well

4. correct the install column as well

5. correct the price column as well

6. rectify the data columns as well

In [71]:
data["Reviews"].head(10)

0       159
1       967
2     87510
3    215644
4       967
5       167
6       178
7     36815
8     13791
9       121
Name: Reviews, dtype: object

In [69]:
data["Reviews"][0]

'159'

In [68]:
data.Reviews.str

In [72]:
data["Installs"].str.replace("+","")

0            10,000
1           500,000
2         5,000,000
3        50,000,000
4           100,000
            ...
10836         5,000
10837           100
10838         1,000
10839         1,000
10840    10,000,000
Name: Installs, Length: 10358, dtype: object

In [74]:
data_copy["Size"]

0                       19M
1                       14M
2                      8.7M
3                       25M
4                      2.8M
                ...
10836                   53M
10837                  3.6M
10838                  9.5M
10839    Varies with device
10840                   19M
Name: Size, Length: 10357, dtype: object

# 2.

In [75]:
data_copy["Size"].value_counts()

Size
Varies with device    1526
11M                    188
13M                    186
12M                    186
14M                    182
                      ...
23k                      1
981k                     1
784k                     1
280k                     1
24k                      1
Name: count, Length: 461, dtype: int64

In [76]:
data_copy["Size"].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '470k',
       '226k', '240k', '89k', '234k', '257k', '861k', '467k', '157k',
       '44k', '676k', '67k', '552k', '885k', '1020k', '582k', '619k'],
      dtype=object)

In [ ]:
1mb=1024kb
14*1024     #it will be in kb

In [77]:
1000

1000

In [ ]:
19M==19000

411k==411

In [81]:
data_copy["Size"]=data_copy["Size"].str.replace("M","000")

In [82]:
data_copy

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7000,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8000,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53000,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6000,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5000,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19000,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [83]:
#i want to remove k
data_copy["Size"]=data_copy["Size"].str.replace("k","")

In [84]:
data_copy["Size"].unique()

array(['19000', '14000', '8.7000', '25000', '2.8000', '5.6000', '29000',
       '33000', '3.1000', '28000', '12000', '20000', '21000', '37000',
       '2.7000', '5.5000', '17000', '39000', '31000', '4.2000', '7.0000',
       '23000', '6.0000', '6.1000', '4.6000', '9.2000', '5.2000', '11000',
       '24000', 'Varies with device', '9.4000', '15000', '10000',
       '1.2000', '26000', '8.0000', '7.9000', '56000', '57000', '35000',
       '54000', '201', '3.6000', '5.7000', '8.6000', '2.4000', '27000',
       '2.5000', '16000', '3.4000', '8.9000', '3.9000', '2.9000', '38000',
       '32000', '5.4000', '18000', '1.1000', '2.2000', '4.5000', '9.8000',
       '52000', '9.0000', '6.7000', '30000', '2.6000', '7.1000', '3.7000',
       '22000', '7.4000', '6.4000', '3.2000', '8.2000', '9.9000',
       '4.9000', '9.5000', '5.0000', '5.9000', '13000', '73000', '6.8000',
       '3.5000', '4.0000', '2.3000', '7.2000', '2.1000', '42000',
       '7.3000', '9.1000', '55000', '23', '6.5000', '1.5000', '7.5000',
       '51000', '41000', '48000', '8.5000', '46000', '8.3000', '4.3000',
       '4.7000', '3.3000', '40000', '7.8000', '8.8000', '6.6000',
       '5.1000', '61000', '66000', '79', '8.4000', '118', '44000', '695',
       '1.6000', '6.2000', '18', '53000', '1.4000', '3.0000', '5.8000',
       '3.8000', '9.6000', '45000', '63000', '49000', '77000', '4.4000',
       '4.8000', '70000', '6.9000', '9.3000', '10.0000', '8.1000',
       '36000', '84000', '97000', '2.0000', '1.9000', '1.8000', '5.3000',
       '47000', '556', '526', '76000', '7.6000', '59000', '9.7000',
       '78000', '72000', '43000', '7.7000', '6.3000', '334', '34000',
       '93000', '65000', '79000', '100000', '58000', '50000', '68000',
       '64000', '67000', '60000', '94000', '232', '99000', '624', '95000',
       '8.5', '41', '292', '11', '80000', '1.7000', '74000', '62000',
       '69000', '75000', '98000', '85000', '82000', '96000', '87000',
       '71000', '86000', '91000', '81000', '92000', '83000', '88000',
       '704', '862', '899', '378', '266', '375', '1.3000', '975', '980',
       '4.1000', '89000', '696', '544', '525', '920', '779', '853', '720',
       '713', '772', '318', '58', '241', '196', '857', '51', '953', '865',
       '251', '930', '540', '313', '746', '203', '26', '314', '239',
       '371', '220', '730', '756', '91', '293', '17', '74', '14', '317',
       '78', '924', '902', '818', '81', '939', '169', '45', '475', '965',
       '90000', '545', '61', '283', '655', '714', '93', '872', '121',
       '322', '1.0000', '976', '172', '238', '549', '206', '954', '444',
       '717', '210', '609', '308', '705', '306', '904', '473', '175',
       '350', '383', '454', '421', '70', '812', '442', '842', '417',
       '412', '459', '478', '335', '782', '721', '430', '429', '192',
       '200', '460', '728', '496', '816', '414', '506', '887', '613',
       '243', '569', '778', '683', '592', '319', '186', '840', '647',
       '191', '373', '437', '598', '716', '585', '982', '222', '219',
       '55', '948', '323', '691', '511', '951', '963', '25', '554', '351',
       '27', '82', '208', '913', '514', '551', '29', '103', '898', '743',
       '116', '153', '209', '353', '499', '173', '597', '809', '122',
       '411', '400', '801', '787', '237', '50', '643', '986', '97', '516',
       '837', '780', '961', '269', '20', '498', '600', '749', '642',
       '881', '72', '656', '601', '221', '228', '108', '940', '176', '33',
       '663', '34', '942', '259', '164', '458', '245', '629', '28', '288',
       '775', '785', '636', '916', '994', '309', '485', '914', '903',
       '608', '500', '54', '562', '847', '957', '688', '811', '270', '48',
       '329', '523', '921', '874', '981', '784', '280', '24', '518',
       '754', '892', '154', '860', '364', '387', '626', '161', '879',
       '39', '970', '170', '141', '160', '144', '143', '190', '376',
       '193', '246', '73', '658', '992', '253', '420', '404', '470',
       '226', '240', '89', '234', '257', '861', '467', '157', '44', '676',
       '67', '552', '885', '1020', '582', '619'], dtype=object)

In [85]:
data["Size"].unique()    #before value it was like this

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '1,000+',
       '470k', '226k', '240k', '89k', '234k', '257k', '861k', '467k',
       '157k', '44k', '676k', '67k', '552k', '885k', '1020k', '582k',
       '619k'], dtype=object)

In [91]:
import numpy as np
data_copy["Size"]=data_copy["Size"].str.replace('Varies with device',str(np.nan))

In [92]:
data_copy["Size"].unique()

array(['19000', '14000', '8.7000', '25000', '2.8000', '5.6000', '29000',
       '33000', '3.1000', '28000', '12000', '20000', '21000', '37000',
       '2.7000', '5.5000', '17000', '39000', '31000', '4.2000', '7.0000',
       '23000', '6.0000', '6.1000', '4.6000', '9.2000', '5.2000', '11000',
       '24000', 'nan', '9.4000', '15000', '10000', '1.2000', '26000',
       '8.0000', '7.9000', '56000', '57000', '35000', '54000', '201',
       '3.6000', '5.7000', '8.6000', '2.4000', '27000', '2.5000', '16000',
       '3.4000', '8.9000', '3.9000', '2.9000', '38000', '32000', '5.4000',
       '18000', '1.1000', '2.2000', '4.5000', '9.8000', '52000', '9.0000',
       '6.7000', '30000', '2.6000', '7.1000', '3.7000', '22000', '7.4000',
       '6.4000', '3.2000', '8.2000', '9.9000', '4.9000', '9.5000',
       '5.0000', '5.9000', '13000', '73000', '6.8000', '3.5000', '4.0000',
       '2.3000', '7.2000', '2.1000', '42000', '7.3000', '9.1000', '55000',
       '23', '6.5000', '1.5000', '7.5000', '51000', '41000', '48000',
       '8.5000', '46000', '8.3000', '4.3000', '4.7000', '3.3000', '40000',
       '7.8000', '8.8000', '6.6000', '5.1000', '61000', '66000', '79',
       '8.4000', '118', '44000', '695', '1.6000', '6.2000', '18', '53000',
       '1.4000', '3.0000', '5.8000', '3.8000', '9.6000', '45000', '63000',
       '49000', '77000', '4.4000', '4.8000', '70000', '6.9000', '9.3000',
       '10.0000', '8.1000', '36000', '84000', '97000', '2.0000', '1.9000',
       '1.8000', '5.3000', '47000', '556', '526', '76000', '7.6000',
       '59000', '9.7000', '78000', '72000', '43000', '7.7000', '6.3000',
       '334', '34000', '93000', '65000', '79000', '100000', '58000',
       '50000', '68000', '64000', '67000', '60000', '94000', '232',
       '99000', '624', '95000', '8.5', '41', '292', '11', '80000',
       '1.7000', '74000', '62000', '69000', '75000', '98000', '85000',
       '82000', '96000', '87000', '71000', '86000', '91000', '81000',
       '92000', '83000', '88000', '704', '862', '899', '378', '266',
       '375', '1.3000', '975', '980', '4.1000', '89000', '696', '544',
       '525', '920', '779', '853', '720', '713', '772', '318', '58',
       '241', '196', '857', '51', '953', '865', '251', '930', '540',
       '313', '746', '203', '26', '314', '239', '371', '220', '730',
       '756', '91', '293', '17', '74', '14', '317', '78', '924', '902',
       '818', '81', '939', '169', '45', '475', '965', '90000', '545',
       '61', '283', '655', '714', '93', '872', '121', '322', '1.0000',
       '976', '172', '238', '549', '206', '954', '444', '717', '210',
       '609', '308', '705', '306', '904', '473', '175', '350', '383',
       '454', '421', '70', '812', '442', '842', '417', '412', '459',
       '478', '335', '782', '721', '430', '429', '192', '200', '460',
       '728', '496', '816', '414', '506', '887', '613', '243', '569',
       '778', '683', '592', '319', '186', '840', '647', '191', '373',
       '437', '598', '716', '585', '982', '222', '219', '55', '948',
       '323', '691', '511', '951', '963', '25', '554', '351', '27', '82',
       '208', '913', '514', '551', '29', '103', '898', '743', '116',
       '153', '209', '353', '499', '173', '597', '809', '122', '411',
       '400', '801', '787', '237', '50', '643', '986', '97', '516', '837',
       '780', '961', '269', '20', '498', '600', '749', '642', '881', '72',
       '656', '601', '221', '228', '108', '940', '176', '33', '663', '34',
       '942', '259', '164', '458', '245', '629', '28', '288', '775',
       '785', '636', '916', '994', '309', '485', '914', '903', '608',
       '500', '54', '562', '847', '957', '688', '811', '270', '48', '329',
       '523', '921', '874', '981', '784', '280', '24', '518', '754',
       '892', '154', '860', '364', '387', '626', '161', '879', '39',
       '970', '170', '141', '160', '144', '143', '190', '376', '193',
       '246', '73', '658', '992', '253', '420', '404', '470', '226',
       '240', '89', '234', '257', '861', '467', '157', '44', '676', '67',
       '552', '885', '1020', '582', '619'], dtype=object)

In [93]:
data_copy["Size"].dtype     #getting object i want to convert how?

dtype('O')

In [98]:
data_copy["Size"]=data_copy["Size"].astype("float")

In [99]:
data_copy["Size"].unique()

array([1.90e+04, 1.40e+04, 8.70e+00, 2.50e+04, 2.80e+00, 5.60e+00,
       2.90e+04, 3.30e+04, 3.10e+00, 2.80e+04, 1.20e+04, 2.00e+04,
       2.10e+04, 3.70e+04, 2.70e+00, 5.50e+00, 1.70e+04, 3.90e+04,
       3.10e+04, 4.20e+00, 7.00e+00, 2.30e+04, 6.00e+00, 6.10e+00,
       4.60e+00, 9.20e+00, 5.20e+00, 1.10e+04, 2.40e+04,      nan,
       9.40e+00, 1.50e+04, 1.00e+04, 1.20e+00, 2.60e+04, 8.00e+00,
       7.90e+00, 5.60e+04, 5.70e+04, 3.50e+04, 5.40e+04, 2.01e+02,
       3.60e+00, 5.70e+00, 8.60e+00, 2.40e+00, 2.70e+04, 2.50e+00,
       1.60e+04, 3.40e+00, 8.90e+00, 3.90e+00, 2.90e+00, 3.80e+04,
       3.20e+04, 5.40e+00, 1.80e+04, 1.10e+00, 2.20e+00, 4.50e+00,
       9.80e+00, 5.20e+04, 9.00e+00, 6.70e+00, 3.00e+04, 2.60e+00,
       7.10e+00, 3.70e+00, 2.20e+04, 7.40e+00, 6.40e+00, 3.20e+00,
       8.20e+00, 9.90e+00, 4.90e+00, 9.50e+00, 5.00e+00, 5.90e+00,
       1.30e+04, 7.30e+04, 6.80e+00, 3.50e+00, 4.00e+00, 2.30e+00,
       7.20e+00, 2.10e+00, 4.20e+04, 7.30e+00, 9.10e+00, 5.50e+04,
       2.30e+01, 6.50e+00, 1.50e+00, 7.50e+00, 5.10e+04, 4.10e+04,
       4.80e+04, 8.50e+00, 4.60e+04, 8.30e+00, 4.30e+00, 4.70e+00,
       3.30e+00, 4.00e+04, 7.80e+00, 8.80e+00, 6.60e+00, 5.10e+00,
       6.10e+04, 6.60e+04, 7.90e+01, 8.40e+00, 1.18e+02, 4.40e+04,
       6.95e+02, 1.60e+00, 6.20e+00, 1.80e+01, 5.30e+04, 1.40e+00,
       3.00e+00, 5.80e+00, 3.80e+00, 9.60e+00, 4.50e+04, 6.30e+04,
       4.90e+04, 7.70e+04, 4.40e+00, 4.80e+00, 7.00e+04, 6.90e+00,
       9.30e+00, 1.00e+01, 8.10e+00, 3.60e+04, 8.40e+04, 9.70e+04,
       2.00e+00, 1.90e+00, 1.80e+00, 5.30e+00, 4.70e+04, 5.56e+02,
       5.26e+02, 7.60e+04, 7.60e+00, 5.90e+04, 9.70e+00, 7.80e+04,
       7.20e+04, 4.30e+04, 7.70e+00, 6.30e+00, 3.34e+02, 3.40e+04,
       9.30e+04, 6.50e+04, 7.90e+04, 1.00e+05, 5.80e+04, 5.00e+04,
       6.80e+04, 6.40e+04, 6.70e+04, 6.00e+04, 9.40e+04, 2.32e+02,
       9.90e+04, 6.24e+02, 9.50e+04, 4.10e+01, 2.92e+02, 1.10e+01,
       8.00e+04, 1.70e+00, 7.40e+04, 6.20e+04, 6.90e+04, 7.50e+04,
       9.80e+04, 8.50e+04, 8.20e+04, 9.60e+04, 8.70e+04, 7.10e+04,
       8.60e+04, 9.10e+04, 8.10e+04, 9.20e+04, 8.30e+04, 8.80e+04,
       7.04e+02, 8.62e+02, 8.99e+02, 3.78e+02, 2.66e+02, 3.75e+02,
       1.30e+00, 9.75e+02, 9.80e+02, 4.10e+00, 8.90e+04, 6.96e+02,
       5.44e+02, 5.25e+02, 9.20e+02, 7.79e+02, 8.53e+02, 7.20e+02,
       7.13e+02, 7.72e+02, 3.18e+02, 5.80e+01, 2.41e+02, 1.96e+02,
       8.57e+02, 5.10e+01, 9.53e+02, 8.65e+02, 2.51e+02, 9.30e+02,
       5.40e+02, 3.13e+02, 7.46e+02, 2.03e+02, 2.60e+01, 3.14e+02,
       2.39e+02, 3.71e+02, 2.20e+02, 7.30e+02, 7.56e+02, 9.10e+01,
       2.93e+02, 1.70e+01, 7.40e+01, 1.40e+01, 3.17e+02, 7.80e+01,
       9.24e+02, 9.02e+02, 8.18e+02, 8.10e+01, 9.39e+02, 1.69e+02,
       4.50e+01, 4.75e+02, 9.65e+02, 9.00e+04, 5.45e+02, 6.10e+01,
       2.83e+02, 6.55e+02, 7.14e+02, 9.30e+01, 8.72e+02, 1.21e+02,
       3.22e+02, 1.00e+00, 9.76e+02, 1.72e+02, 2.38e+02, 5.49e+02,
       2.06e+02, 9.54e+02, 4.44e+02, 7.17e+02, 2.10e+02, 6.09e+02,
       3.08e+02, 7.05e+02, 3.06e+02, 9.04e+02, 4.73e+02, 1.75e+02,
       3.50e+02, 3.83e+02, 4.54e+02, 4.21e+02, 7.00e+01, 8.12e+02,
       4.42e+02, 8.42e+02, 4.17e+02, 4.12e+02, 4.59e+02, 4.78e+02,
       3.35e+02, 7.82e+02, 7.21e+02, 4.30e+02, 4.29e+02, 1.92e+02,
       2.00e+02, 4.60e+02, 7.28e+02, 4.96e+02, 8.16e+02, 4.14e+02,
       5.06e+02, 8.87e+02, 6.13e+02, 2.43e+02, 5.69e+02, 7.78e+02,
       6.83e+02, 5.92e+02, 3.19e+02, 1.86e+02, 8.40e+02, 6.47e+02,
       1.91e+02, 3.73e+02, 4.37e+02, 5.98e+02, 7.16e+02, 5.85e+02,
       9.82e+02, 2.22e+02, 2.19e+02, 5.50e+01, 9.48e+02, 3.23e+02,
       6.91e+02, 5.11e+02, 9.51e+02, 9.63e+02, 2.50e+01, 5.54e+02,
       3.51e+02, 2.70e+01, 8.20e+01, 2.08e+02, 9.13e+02, 5.14e+02,
       5.51e+02, 2.90e+01, 1.03e+02, 8.98e+02, 7.43e+02, 1.16e+02,
       1.53e+02, 2.09e+02, 3.53e+02, 4.99e+02, 1.73e+02, 5.97e+02,
       8.09e+02, 1.22e+02, 4.11e+02, 4.00e+02, 8.01e+02, 7.87e+02,
       2.37e+02, 5.00e+01, 6.43e+02, 9.86e+02, 9.70e+01, 5.16e+02,
       8.37e+02, 7.80e+02, 9.61e+02, 2.69e+02, 2.00e+01, 4.98e+02,
       6.00e+02, 7.49e+02, 6.42e+02, 8.81e+02, 7.20e+01, 6.56e+02,
       6.01e+02, 2.21e+02, 2.28e+02, 1.08e+02, 9.40e+02, 1.76e+02,
       3.30e+01, 6.63e+02, 3.40e+01, 9.42e+02, 2.59e+02, 1.64e+02,
       4.58e+02, 2.45e+02, 6.29e+02, 2.80e+01, 2.88e+02, 7.75e+02,
       7.85e+02, 6.36e+02, 9.16e+02, 9.94e+02, 3.09e+02, 4.85e+02,
       9.14e+02, 9.03e+02, 6.08e+02, 5.00e+02, 5.40e+01, 5.62e+02,
       8.47e+02, 9.57e+02, 6.88e+02, 8.11e+02, 2.70e+02, 4.80e+01,
       3.29e+02, 5.23e+02, 9.21e+02, 8.74e+02, 9.81e+02, 7.84e+02,
       2.80e+02, 2.40e+01, 5.18e+02, 7.54e+02, 8.92e+02, 1.54e+02,
       8.60e+02, 3.64e+02, 3.87e+02, 6.26e+02, 1.61e+02, 8.79e+02,
       3.90e+01, 9.70e+02, 1.70e+02, 1.41e+02, 1.60e+02, 1.44e+02,
       1.43e+02, 1.90e+02, 3.76e+02, 1.93e+02, 2.46e+02, 7.30e+01,
       6.58e+02, 9.92e+02, 2.53e+02, 4.20e+02, 4.04e+02, 4.70e+02,
       2.26e+02, 2.40e+02, 8.90e+01, 2.34e+02, 2.57e+02, 8.61e+02,
       4.67e+02, 1.57e+02, 4.40e+01, 6.76e+02, 6.70e+01, 5.52e+02,
       8.85e+02, 1.02e+03, 5.82e+02, 6.19e+02])

In [100]:
data   #my original data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [103]:
14MB

SyntaxError: invalid decimal literal (3576413637.py, line 1)

In [104]:
14*1000 kb

14000

In [ ]:
8.7MBb

In [105]:
8.7*1000

8700.0

In [ ]:
8700.0kb

In [ ]:
8.7MB
8.7000

In [107]:
for value in data_copy["Size"]:
    if value<10:
        data_copy["Size"]=data_copy["Size"].replace(value,value*1000)

In [109]:
for i in data_copy["Size"]:
    print(i)

19000.0
14000.0
8700.0
25000.0
2800.0
5600.0
19000.0
29000.0
33000.0
3100.0
28000.0
12000.0
20000.0
21000.0
37000.0
2700.0
5500.0
17000.0
39000.0
31000.0
14000.0
12000.0
4200.0
7000.0
23000.0
6000.0
25000.0
6100.0
4600.0
4200.0
9200.0
5200.0
11000.0
11000.0
4200.0
9200.0
24000.0
nan
11000.0
9400.0
15000.0
10000.0
nan
1200.0
12000.0
24000.0
26000.0
8000.0
7900.0
25000.0
56000.0
57000.0
nan
35000.0
33000.0
33000.0
5600.0
54000.0
201.0
3600.0
5700.0
17000.0
8600.0
2400.0
27000.0
2700.0
2500.0
nan
nan
7000.0
35000.0
16000.0
16000.0
nan
17000.0
3400.0
8900.0
3900.0
2900.0
38000.0
32000.0
37000.0
15000.0
5400.0
18000.0
nan
38000.0
1100.0
nan
nan
7900.0
35000.0
nan
17000.0
19000.0
14000.0
2200.0
4500.0
17000.0
14000.0
9800.0
21000.0
nan
52000.0
14000.0
25000.0
9000.0
nan
12000.0
nan
35000.0
6700.0
30000.0
5700.0
2900.0
17000.0
2900.0
nan
nan
2600.0
4200.0
7100.0
57000.0
3700.0
22000.0
24000.0
7400.0
21000.0
3400.0
2900.0
3100.0
6400.0
3200.0
8200.0
9900.0
2900.0
23000.0
4600.0
3100.0
nan
4900.0
9500.0
nan
nan
nan
nan
nan
4200.0
5400.0
nan
2800.0
5000.0
nan
5900.0
13000.0
7100.0
6700.0
nan
17000.0
19000.0
6700.0
21000.0
nan
2700.0
37000.0
15000.0
23000.0
19000.0
23000.0
73000.0
4900.0
6800.0
nan
nan
2900.0
3500.0
4000.0
21000.0
2300.0
nan
7200.0
10000.0
6100.0
2100.0
42000.0
7300.0
30000.0
nan
nan
nan
29000.0
nan
nan
nan
35000.0
9100.0
25000.0
3900.0
18000.0
12000.0
21000.0
nan
nan
nan
nan
55000.0
3200.0
nan
nan
23.0
16000.0
nan
14000.0
37000.0
nan
nan
11000.0
25000.0
7300.0
6500.0
25000.0
3100.0
nan
1500.0
7500.0
8600.0
nan
1200.0
nan
nan
39000.0
14000.0
19000.0
6800.0
39000.0
14000.0
20000.0
nan
26000.0
51000.0
41000.0
20000.0
nan
12000.0
48000.0
10000.0
22000.0
11000.0
8500.0
8600.0
nan
28000.0
28000.0
9000.0
46000.0
nan
14000.0
26000.0
23000.0
nan
nan
35000.0
nan
29000.0
nan
4900.0
27000.0
32000.0
12000.0
15000.0
11000.0
28000.0
2200.0
3400.0
8300.0
4300.0
4700.0
10000.0
15000.0
7100.0
21000.0
6100.0
nan
15000.0
11000.0
29000.0
3300.0
nan
22000.0
40000.0
10000.0
9100.0
4700.0
38000.0
nan
6700.0
37000.0
nan
7800.0
19000.0
5700.0
35000.0
nan
nan
17000.0
nan
nan
nan
nan
nan
8800.0
nan
16000.0
11000.0
11000.0
nan
15000.0
6600.0
nan
6600.0
nan
nan
5100.0
nan
18000.0
4000.0
nan
nan
nan
37000.0
nan
22000.0
nan
3300.0
32000.0
37000.0
nan
nan
nan
nan
nan
17000.0
nan
nan
35000.0
40000.0
61000.0
66000.0
nan
11000.0
79.0
nan
nan
25000.0
14000.0
nan
nan
nan
nan
nan
24000.0
17000.0
8300.0
nan
8200.0
nan
nan
nan
nan
8400.0
nan
nan
4000.0
32000.0
nan
nan
nan
6100.0
nan
2800.0
nan
nan
3300.0
40000.0
2200.0
nan
4300.0
4700.0
2300.0
2300.0
nan
11000.0
2700.0
13000.0
3700.0
10000.0
13000.0
10000.0
13000.0
8800.0
5500.0
20000.0
29000.0
nan
nan
11000.0
nan
17000.0
17000.0
nan
nan
118.0
nan
16000.0
5100.0
nan
44000.0
7300.0
30000.0
695.0
nan
1600.0
19000.0
nan
nan
nan
nan
23000.0
26000.0
nan
6200.0
20000.0
18.0
1200.0
17000.0
nan
15000.0
nan
56000.0
12000.0
11000.0
29000.0
nan
40000.0
nan
53000.0
3100.0
24000.0
23000.0
5000.0
44000.0
27000.0
6100.0
nan
21000.0
11000.0
21000.0
24000.0
31000.0
27000.0
6200.0
nan
12000.0
8000.0
5900.0
7900.0
5000.0
1400.0
13000.0
40000.0
13000.0
19000.0
5000.0
19000.0
27000.0
3000.0
13000.0
7200.0
25000.0
nan
5700.0
5500.0
nan
6500.0
5800.0
nan
3800.0
41000.0
7900.0
2800.0
20000.0
15000.0
28000.0
9600.0
13000.0
9400.0
27000.0
45000.0
15000.0
38000.0
31000.0
6100.0
27000.0
32000.0
13000.0
63000.0
44000.0
nan
16000.0
28000.0
nan
5900.0
13000.0
9000.0
20000.0
7900.0
28000.0
49000.0
27000.0
18000.0
14000.0
27000.0
38000.0
27000.0
7200.0
21000.0
8800.0
38000.0
nan
11000.0
6500.0
26000.0
19000.0
6100.0
77000.0
9500.0
14000.0
38000.0
16000.0
3400.0
4700.0
5000.0
4900.0
4900.0
16000.0
3900.0
4400.0
4800.0
4500.0
70000.0
4900.0
3700.0
4900.0
16000.0
4600.0
3600.0
21000.0
13000.0
8700.0
9200.0
6900.0
39000.0
8000.0
3900.0
14000.0
11000.0
13000.0
9300.0
5000.0
10.0
5000.0
5000.0
3600.0
19000.0
5000.0
9800.0
14000.0
5000.0
4900.0
5500.0
11000.0
3800.0
5000.0
8200.0
21000.0
12000.0
10000.0
3300.0
25000.0
15000.0
10000.0
4900.0
4400.0
3500.0
7800.0
9000.0
15000.0
19000.0
56000.0
4700.0
nan
25000.0
29000.0
8100.0
13000.0
14000.0
3700.0
3500.0
4500.0
36000.0
4500.0
19000.0
14000.0
7900.0
9300.0
nan
18000.0
18000.0
21000.0
3300.0
24000.0
39000.0
3200.0
5100.0
11000.0
27000.0
37000.0
nan
26000.0
11000.0
nan
41000.0
49000.0
21000.0
8100.0
51000.0
14000.0
18000.0
3000.0
19000.0
nan
22000.0
6900.0
7400.0
84000.0
25000.0
18000.0
nan
2500.0
3900.0
nan
21000.0
27000.0
nan
nan
18000.0
nan
10000.0
nan
nan
nan
97000.0
17000.0
nan
nan
2000.0
1900.0
1800.0
1800.0
17000.0
5300.0
nan
5400.0
5400.0
5400.0
15000.0
5300.0
48000.0
5400.0
47000.0
556.0
29000.0
2300.0
nan
4400.0
6600.0
nan
526.0
12000.0
nan
29000.0
nan
nan
nan
nan
10000.0
76000.0
nan
nan
18000.0
21000.0
nan
6900.0
14000.0
76000.0
11000.0
19000.0
6500.0
7000.0
3300.0
21000.0
nan
2600.0
21000.0
5200.0
18000.0
nan
16000.0
15000.0
1200.0
nan
18000.0
1800.0
7600.0
nan
nan
59000.0
6900.0
41000.0
nan
21000.0
21000.0
21000.0
nan
nan
7300.0
59000.0
41000.0
7600.0
nan
13000.0
63000.0
44000.0
24000.0
24000.0
nan
4500.0
nan
11000.0
nan
4600.0
nan
nan
3300.0
6500.0
nan
nan
nan
12000.0
nan
5600.0
9700.0
15000.0
nan
52000.0
nan
nan
4500.0
nan
49000.0
18000.0
13000.0
4000.0
16000.0
17000.0
nan
24000.0
nan
12000.0
nan
78000.0
nan
25000.0
57000.0
nan
9100.0
39000.0
nan
nan
8500.0
12000.0
72000.0
12000.0
nan
16000.0
9600.0
nan
22000.0
nan
13000.0
nan
12000.0
nan
23000.0
20000.0
25000.0
17000.0
nan
19000.0
21000.0
19000.0
nan
nan
nan
nan
19000.0
4400.0
19000.0
nan
11000.0
nan
nan
13000.0
17000.0
20000.0
21000.0
15000.0
19000.0
7200.0
32000.0
nan
nan
44000.0
19000.0
nan
nan
nan
nan
30000.0
nan
57000.0
35000.0
44000.0
nan
20000.0
19000.0
43000.0
nan
nan
3600.0
7700.0
44000.0
12000.0
53000.0
77000.0
nan
9500.0
36000.0
6300.0
5900.0
nan
12000.0
2800.0
26000.0
8700.0
16000.0
53000.0
nan
14000.0
8900.0
11000.0
334.0
24000.0
13000.0
nan
2800.0
9700.0
1400.0
nan
3500.0
61000.0
6000.0
2300.0
9000.0
11000.0
27000.0
3600.0
nan
29000.0
4400.0
21000.0
13000.0
27000.0
11000.0
24000.0
6100.0
6300.0
23000.0
34000.0
3800.0
nan
nan
42000.0
nan
19000.0
70000.0
32000.0
93000.0
nan
nan
nan
40000.0
24000.0
nan
20000.0
15000.0
28000.0
10000.0
nan
nan
nan
14000.0
nan
42000.0
65000.0
37000.0
nan
39000.0
47000.0
79000.0
18000.0
nan
100000.0
32000.0
46000.0
nan
9800.0
8200.0
18000.0
nan
39000.0
44000.0
nan
5000.0
21000.0
22000.0
23000.0
nan
nan
27000.0
nan
32000.0
7400.0
24000.0
22000.0
nan
10000.0
17000.0
38000.0
46000.0
3800.0
9300.0
8400.0
28000.0
nan
9700.0
11000.0
nan
7400.0
19000.0
16000.0
14000.0
22000.0
25000.0
3600.0
nan
nan
4500.0
nan
23000.0
nan
nan
nan
4200.0
nan
58000.0
22000.0
nan
1400.0
nan
9100.0
nan
nan
nan
nan
21000.0
nan
11000.0
38000.0
12000.0
45000.0
50000.0
47000.0
23000.0
46000.0
45000.0
50000.0
24000.0
33000.0
nan
12000.0
53000.0
14000.0
68000.0
37000.0
79000.0
32000.0
46000.0
40000.0
32000.0
nan
24000.0
42000.0
12000.0
13000.0
13000.0
4900.0
8900.0
nan
19000.0
nan
14000.0
64000.0
8400.0
11000.0
66000.0
nan
41000.0
15000.0
35000.0
36000.0
17000.0
25000.0
35000.0
10000.0
nan
12000.0
nan
11000.0
nan
nan
17000.0
43000.0
41000.0
nan
43000.0
16000.0
39000.0
13000.0
30000.0
7100.0
23000.0
17000.0
18000.0
nan
17000.0
nan
15000.0
22000.0
nan
9000.0
7200.0
nan
nan
2300.0
27000.0
nan
8200.0
76000.0
22000.0
nan
19000.0
nan
nan
28000.0
nan
nan
nan
25000.0
30000.0
8500.0
nan
17000.0
34000.0
34000.0
nan
17000.0
16000.0
nan
15000.0
2200.0
11000.0
6900.0
13000.0
11000.0
2900.0
25000.0
7000.0
27000.0
7500.0
nan
15000.0
9400.0
6400.0
5500.0
3900.0
55000.0
28000.0
nan
8800.0
nan
4000.0
6900.0
11000.0
nan
5500.0
nan
15000.0
4300.0
nan
7100.0
58000.0
nan
nan
18000.0
nan
1500.0
6500.0
11000.0
67000.0
nan
57000.0
59000.0
48000.0
57000.0
13000.0
nan
nan
nan
31000.0
10000.0
57000.0
nan
21000.0
25000.0
93000.0
60000.0
27000.0
54000.0
nan
nan
59000.0
nan
78000.0
55000.0
nan
nan
nan
35000.0
nan
43000.0
39000.0
4200.0
44000.0
45000.0
nan
28000.0
29000.0
12000.0
15000.0
31000.0
nan
nan
nan
nan
20000.0
39000.0
94000.0
nan
41000.0
49000.0
22000.0
nan
23000.0
28000.0
7200.0
6500.0
nan
24000.0
nan
nan
20000.0
nan
15000.0
nan
55000.0
nan
38000.0
32000.0
nan
nan
40000.0
nan
23000.0
6100.0
nan
58000.0
55000.0
nan
nan
nan
nan
nan
nan
19000.0
3800.0
18000.0
57000.0
5500.0
nan
5700.0
51000.0
9400.0
3300.0
nan
4000.0
4300.0
nan
3600.0
9900.0
37000.0
nan
nan
40000.0
73000.0
nan
23000.0
10000.0
8400.0
nan
nan
nan
41000.0
nan
34000.0
7500.0
nan
12000.0
7700.0
21000.0
18000.0
40000.0
nan
8700.0
nan
8600.0
nan
18000.0
7500.0
9100.0
13000.0
nan
15000.0
nan
19000.0
nan
nan
5100.0
26000.0
8300.0
27000.0
7900.0
nan
27000.0
5100.0
15000.0
3100.0
16000.0
9200.0
nan
nan
10000.0
2600.0
13000.0
1900.0
7000.0
15000.0
4200.0
7800.0
77000.0
5700.0
5900.0
7600.0
5800.0
nan
5800.0
5300.0
5500.0
25000.0
35000.0
30000.0
nan
nan
nan
16000.0
nan
15000.0
21000.0
1800.0
4300.0
10000.0
3700.0
232.0
99000.0
624.0
6900.0
7000.0
7000.0
6400.0
nan
16000.0
5900.0
95000.0
8500.0
20000.0
2500.0
50000.0
10000.0
18000.0
12000.0
2500.0
2100.0
22000.0
41.0
22000.0
292.0
5500.0
nan
2500.0
8100.0
28000.0
24000.0
3100.0
3400.0
11.0
13000.0
19000.0
9500.0
21000.0
9400.0
2400.0
36000.0
55000.0
32000.0
34000.0
5100.0
100000.0
80000.0
3300.0
28000.0
5000.0
11000.0
55000.0
7100.0
3200.0
4400.0
16000.0
6300.0
45000.0
23000.0
37000.0
13000.0
8100.0
13000.0
14000.0
30000.0
36000.0
3000.0
1400.0
39000.0
1800.0
1700.0
19000.0
15000.0
10.0
2700.0
16000.0
21000.0
20000.0
14000.0
76000.0
18000.0
12000.0
6200.0
nan
6800.0
nan
24000.0
19000.0
13000.0
15000.0
13000.0
nan
44000.0
nan
9700.0
13000.0
4500.0
4500.0
29000.0
12000.0
12000.0
nan
4600.0
10000.0
33000.0
33000.0
13000.0
15000.0
23000.0
7700.0
nan
15000.0
25000.0
nan
3000.0
22000.0
nan
nan
7500.0
24000.0
nan
44000.0
nan
nan
14000.0
67000.0
76000.0
74000.0
23000.0
46000.0
24000.0
nan
97000.0
62000.0
24000.0
33000.0
7800.0
46000.0
69000.0
75000.0
67000.0
50000.0
98000.0
nan
4900.0
37000.0
18000.0
52000.0
nan
78000.0
3900.0
59000.0
97000.0
11000.0
38000.0
nan
nan
nan
nan
85000.0
78000.0
63000.0
nan
24000.0
69000.0
75000.0
nan
70000.0
63000.0
99000.0
49000.0
nan
76000.0
67000.0
24000.0
52000.0
74000.0
69000.0
82000.0
nan
96000.0
99000.0
46000.0
nan
99000.0
87000.0
3900.0
67000.0
53000.0
7800.0
nan
97000.0
nan
nan
59000.0
46000.0
75000.0
50000.0
62000.0
nan
23000.0
72000.0
70000.0
18000.0
nan
35000.0
78000.0
25000.0
74000.0
97000.0
17000.0
53000.0
nan
11000.0
60000.0
57000.0
14000.0
67000.0
33000.0
76000.0
nan
40000.0
59000.0
52000.0
nan
100000.0
nan
nan
nan
85000.0
87000.0
33000.0
32000.0
40000.0
29000.0
40000.0
24000.0
38000.0
52000.0
nan
54000.0
71000.0
73000.0
38000.0
62000.0
95000.0
16000.0
39000.0
78000.0
36000.0
nan
31000.0
nan
98000.0
24000.0
85000.0
33000.0
100000.0
36000.0
86000.0
80000.0
79000.0
30000.0
87000.0
91000.0
63000.0
nan
nan
95000.0
48000.0
nan
nan
93000.0
53000.0
82000.0
99000.0
49000.0
25000.0
nan
91000.0
52000.0
56000.0
56000.0
85000.0
81000.0
82000.0
98000.0
77000.0
99000.0
nan
96000.0
96000.0
82000.0
70000.0
63000.0
35000.0
48000.0
84000.0
15000.0
69000.0
46000.0
15000.0
33000.0
48000.0
67000.0
74000.0
57000.0
52000.0
25000.0
nan
36000.0
31000.0
91000.0
nan
92000.0
70000.0
93000.0
52000.0
91000.0
37000.0
64000.0
35000.0
97000.0
93000.0
28000.0
83000.0
99000.0
55000.0
14000.0
81000.0
nan
74000.0
67000.0
52000.0
76000.0
67000.0
50000.0
46000.0
nan
nan
97000.0
98000.0
70000.0
69000.0
3900.0
7800.0
18000.0
24000.0
62000.0
11000.0
nan
87000.0
99000.0
nan
82000.0
94000.0
nan
nan
nan
96000.0
75000.0
nan
14000.0
59000.0
74000.0
29000.0
17000.0
97000.0
78000.0
nan
nan
63000.0
nan
25000.0
29000.0
72000.0
nan
53000.0
nan
33000.0
60000.0
62000.0
78000.0
75000.0
70000.0
99000.0
99000.0
nan
27000.0
70000.0
88000.0
63000.0
82000.0
nan
31000.0
23000.0
nan
59000.0
39000.0
54000.0
48000.0
nan
30000.0
66000.0
32000.0
50000.0
61000.0
49000.0
38000.0
20000.0
nan
nan
66000.0
57000.0
95000.0
nan
nan
32000.0
33000.0
66000.0
75000.0
29000.0
33000.0
52000.0
50000.0
46000.0
12000.0
41000.0
63000.0
53000.0
63000.0
99000.0
nan
20000.0
75000.0
13000.0
46000.0
78000.0
49000.0
100000.0
nan
97000.0
nan
nan
15000.0
33000.0
nan
70000.0
10000.0
77000.0
nan
4900.0
nan
25000.0
23000.0
51000.0
96000.0
nan
nan
nan
70000.0
38000.0
24000.0
nan
20000.0
67000.0
19000.0
51000.0
22000.0
46000.0
21000.0
39000.0
23000.0
26000.0
39000.0
24000.0
15000.0
20000.0
24000.0
44000.0
38000.0
52000.0
14000.0
49000.0
8900.0
nan
56000.0
99000.0
10000.0
6900.0
20000.0
10000.0
19000.0
33000.0
85000.0
48000.0
9600.0
nan
15000.0
nan
50000.0
51000.0
24000.0
13000.0
16000.0
nan
nan
63000.0
15000.0
26000.0
81000.0
79000.0
nan
94000.0
43000.0
45000.0
91000.0
91000.0
53000.0
28000.0
26000.0
56000.0
80000.0
60000.0
nan
67000.0
78000.0
27000.0
nan
63000.0
26000.0
46000.0
83000.0
60000.0
44000.0
82000.0
67000.0
24000.0
78000.0
nan
nan
51000.0
94000.0
16000.0
93000.0
77000.0
32000.0
58000.0
48000.0
69000.0
73000.0
99000.0
16000.0
54000.0
56000.0
68000.0
25000.0
7000.0
54000.0
51000.0
nan
48000.0
44000.0
8700.0
91000.0
97000.0
26000.0
16000.0
nan
53000.0
95000.0
83000.0
78000.0
56000.0
21000.0
26000.0
60000.0
22000.0
58000.0
22000.0
36000.0
37000.0
70000.0
34000.0
49000.0
9800.0
37000.0
nan
55000.0
84000.0
16000.0
92000.0
57000.0
nan
24000.0
6900.0
44000.0
11000.0
16000.0
17000.0
18000.0
16000.0
19000.0
1600.0
47000.0
16000.0
14000.0
nan
75000.0
25000.0
5700.0
nan
17000.0
3500.0
16000.0
42000.0
47000.0
67000.0
26000.0
72000.0
37000.0
1200.0
17000.0
19000.0
23000.0
25000.0
83000.0
97000.0
37000.0
92000.0
48000.0
12000.0
15000.0
83000.0
9500.0
67000.0
nan
nan
nan
63000.0
14000.0
58000.0
22000.0
15000.0
nan
50000.0
59000.0
54000.0
nan
nan
37000.0
25000.0
61000.0
91000.0
17000.0
17000.0
64000.0
41000.0
58000.0
23000.0
71000.0
nan
nan
23000.0
12000.0
704.0
2900.0
25000.0
nan
20000.0
21000.0
5400.0
25000.0
42000.0
32000.0
1800.0
33000.0
3800.0
5800.0
9500.0
19000.0
nan
5000.0
23000.0
862.0
9900.0
24000.0
2400.0
899.0
38000.0
6500.0
14000.0
1200.0
48000.0
378.0
22000.0
4800.0
nan
25000.0
266.0
375.0
62000.0
1200.0
nan
2800.0
95000.0
2600.0
4600.0
nan
5100.0
1800.0
nan
nan
53000.0
39000.0
5300.0
14000.0
8400.0
18000.0
41000.0
100000.0
3400.0
68000.0
2600.0
11000.0
nan
37000.0
nan
9800.0
23000.0
18000.0
7400.0
11000.0
nan
23000.0
34000.0
15000.0
13000.0
24000.0
20000.0
14000.0
69000.0
38000.0
26000.0
2600.0
21000.0
38000.0
16000.0
21000.0
10000.0
22000.0
14000.0
36000.0
16000.0
61000.0
11000.0
8500.0
37000.0
nan
nan
22000.0
17000.0
7700.0
39000.0
30000.0
3700.0
28000.0
16000.0
20000.0
8900.0
97000.0
12000.0
72000.0
nan
21000.0
nan
27000.0
5700.0
6600.0
12000.0
5900.0
20000.0
15000.0
26000.0
3300.0
44000.0
17000.0
5800.0
11000.0
16000.0
6100.0
nan
22000.0
28000.0
6300.0
60000.0
8000.0
20000.0
6400.0
34000.0
70000.0
28000.0
21000.0
38000.0
nan
74000.0
12000.0
13000.0
6800.0
12000.0
5800.0
42000.0
13000.0
1500.0
3200.0
7700.0
1300.0
26000.0
11000.0
nan
3100.0
1800.0
66000.0
5000.0
2900.0
22000.0
16000.0
19000.0
40000.0
23000.0
15000.0
29000.0
16000.0
65000.0
29000.0
20000.0
3800.0
19000.0
25000.0
5100.0
16000.0
1500.0
10.0
22000.0
3600.0
20000.0
20000.0
13000.0
2500.0
3600.0
24000.0
10000.0
25000.0
29000.0
17000.0
53000.0
83000.0
4600.0
4600.0
28000.0
29000.0
46000.0
5700.0
1400.0
12000.0
2200.0
27000.0
18000.0
30000.0
3500.0
4200.0
6900.0
6600.0
7000.0
11000.0
5600.0
29000.0
3300.0
20000.0
7000.0
3300.0
29000.0
7100.0
nan
24000.0
13000.0
34000.0
4300.0
43000.0
69000.0
25000.0
2000.0
40000.0
4300.0
4000.0
17000.0
4400.0
2300.0
40000.0
8400.0
11000.0
2400.0
15000.0
24000.0
86000.0
nan
11000.0
975.0
980.0
6000.0
20000.0
26000.0
13000.0
2700.0
4200.0
28000.0
6100.0
15000.0
1200.0
37000.0
14000.0
2300.0
32000.0
2700.0
2200.0
nan
nan
nan
4000.0
nan
1500.0
nan
3700.0
nan
nan
nan
2800.0
3900.0
3100.0
nan
2800.0
20000.0
9900.0
5300.0
10000.0
2600.0
nan
31000.0
2300.0
6000.0
17000.0
20000.0
62000.0
nan
15000.0
nan
18000.0
5400.0
2800.0
15000.0
nan
5300.0
nan
nan
37000.0
nan
23000.0
nan
nan
nan
28000.0
35000.0
nan
76000.0
nan
34000.0
nan
nan
nan
nan
2700.0
nan
4100.0
nan
nan
nan
nan
85000.0
15000.0
89000.0
nan
20000.0
nan
9300.0
nan
76000.0
34000.0
16000.0
nan
nan
nan
nan
nan
8400.0
20000.0
nan
68000.0
13000.0
50000.0
nan
28000.0
nan
nan
7000.0
23000.0
nan
nan
nan
56000.0
nan
22000.0
15000.0
nan
30000.0
30000.0
27000.0
nan
nan
nan
20000.0
42000.0
nan
18000.0
4200.0
nan
30000.0
33000.0
7900.0
12000.0
15000.0
nan
10000.0
9900.0
9000.0
nan
21000.0
13000.0
11000.0
21000.0
8100.0
nan
nan
12000.0
7300.0
nan
15000.0
22000.0
11000.0
8300.0
nan
20000.0
38000.0
9100.0
24000.0
nan
nan
29000.0
nan
98000.0
25000.0
nan
18000.0
nan
6100.0
14000.0
21000.0
nan
43000.0
15000.0
23000.0
52000.0
nan
nan
57000.0
20000.0
40000.0
17000.0
13000.0
33000.0
nan
29000.0
nan
31000.0
nan
20000.0
13000.0
7300.0
12000.0
8800.0
18000.0
21000.0
34000.0
26000.0
34000.0
2700.0
nan
nan
nan
20000.0
23000.0
nan
42000.0
16000.0
12000.0
6500.0
15000.0
22000.0
nan
6200.0
19000.0
27000.0
1100.0
nan
16000.0
8800.0
24000.0
56000.0
15000.0
nan
14000.0
22000.0
28000.0
59000.0
37000.0
36000.0
9500.0
82000.0
28000.0
nan
nan
9700.0
22000.0
17000.0
nan
nan
7700.0
nan
11000.0
21000.0
19000.0
nan
8700.0
30000.0
25000.0
17000.0
nan
13000.0
23000.0
nan
nan
22000.0
9100.0
8300.0
nan
19000.0
53000.0
nan
17000.0
10000.0
nan
29000.0
46000.0
4500.0
4900.0
nan
24000.0
23000.0
25000.0
26000.0
nan
2000.0
19000.0
9600.0
nan
13000.0
4200.0
16000.0
nan
nan
9500.0
nan
53000.0
6600.0
nan
nan
27000.0
22000.0
nan
50000.0
30000.0
nan
17000.0
18000.0
10.0
9900.0
23000.0
51000.0
35000.0
16000.0
11000.0
74000.0
48000.0
nan
nan
5600.0
1500.0
5700.0
6100.0
1900.0
4000.0
47000.0
nan
nan
22000.0
14000.0
10000.0
nan
6900.0
44000.0
nan
nan
nan
51000.0
nan
43000.0
21000.0
nan
25000.0
3900.0
4000.0
51000.0
nan
nan
9600.0
nan
nan
50000.0
nan
nan
21000.0
nan
31000.0
27000.0
nan
nan
nan
53000.0
34000.0
nan
12000.0
50000.0
47000.0
nan
nan
nan
9200.0
nan
nan
51000.0
24000.0
1600.0
17000.0
31000.0
59000.0
46000.0
45000.0
nan
9800.0
nan
nan
nan
34000.0
20000.0
19000.0
6000.0
nan
15000.0
6500.0
6200.0
nan
nan
nan
nan
nan
nan
14000.0
nan
nan
6100.0
17000.0
24000.0
nan
13000.0
10000.0
10000.0
6900.0
31000.0
nan
nan
28000.0
2600.0
30000.0
13000.0
27000.0
29000.0
18000.0
35000.0
17000.0
nan
18000.0
nan
3000.0
32000.0
24000.0
nan
nan
6600.0
27000.0
25000.0
24000.0
nan
25000.0
33000.0
88000.0
9300.0
nan
nan
84000.0
4700.0
25000.0
12000.0
nan
9900.0
61000.0
25000.0
52000.0
57000.0
nan
41000.0
4600.0
10000.0
23000.0
nan
33000.0
nan
4700.0
2200.0
nan
95000.0
34000.0
nan
9400.0
19000.0
3900.0
nan
21000.0
82000.0
nan
nan
19000.0
nan
26000.0
5200.0
16000.0
nan
6000.0
25000.0
nan
8100.0
35000.0
nan
48000.0
21000.0
32000.0
nan
nan
14000.0
nan
nan
25000.0
nan
58000.0
19000.0
29000.0
81000.0
nan
nan
28000.0
nan
nan
nan
nan
7600.0
33000.0
nan
42000.0
8300.0
14000.0
nan
nan
nan
37000.0
14000.0
nan
21000.0
28000.0
27000.0
nan
39000.0
nan
17000.0
nan
39000.0
51000.0
86000.0
nan
nan
nan
26000.0
nan
46000.0
29000.0
27000.0
14000.0
nan
10000.0
71000.0
15000.0
nan
nan
11000.0
nan
62000.0
80000.0
5400.0
9800.0
nan
nan
nan
7600.0
26000.0
13000.0
nan
62000.0
10.0
nan
57000.0
51000.0
24000.0
nan
29000.0
nan
3100.0
55000.0
19000.0
40000.0
nan
43000.0
50000.0
nan
13000.0
nan
nan
nan
4000.0
nan
44000.0
22000.0
nan
nan
nan
12000.0
nan
46000.0
7600.0
nan
nan
4100.0
8500.0
31000.0
4100.0
nan
22000.0
nan
28000.0
nan
5900.0
nan
nan
nan
3900.0
nan
15000.0
4300.0
nan
nan
nan
nan
5300.0
nan
16000.0
7500.0
nan
nan
nan
3700.0
nan
5800.0
17000.0
nan
8500.0
nan
9100.0
7600.0
2500.0
15000.0
nan
nan
nan
nan
6100.0
nan
17000.0
nan
nan
nan
nan
58000.0
4600.0
16000.0
1300.0
2300.0
1900.0
2700.0
16000.0
11000.0
5300.0
nan
4200.0
nan
9100.0
4300.0
nan
nan
nan
nan
1800.0
nan
8500.0
4400.0
nan
3800.0
11000.0
nan
11000.0
nan
7400.0
5300.0
5400.0
3600.0
nan
4300.0
nan
27000.0
nan
1800.0
3300.0
2000.0
6100.0
9600.0
9600.0
10000.0
8200.0
14000.0
25000.0
9900.0
22000.0
nan
8900.0
nan
2400.0
25000.0
nan
nan
1800.0
17000.0
nan
4100.0
18000.0
14000.0
nan
nan
nan
696.0
4700.0
8100.0
nan
7900.0
4600.0
544.0
3500.0
nan
nan
525.0
2100.0
nan
14000.0
nan
8700.0
21000.0
nan
12000.0
18000.0
17000.0
3800.0
nan
23000.0
14000.0
15000.0
9900.0
12000.0
12000.0
20000.0

In [111]:
data_copy["Size"]=data_copy["Size"]/1000      #all the values are in mb

In [112]:
data_copy.head(8)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19.0,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29.0,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up

In [114]:
data_copy["Installs"]=data_copy["Installs"].str.replace("+","")

In [115]:
data_copy["Installs"]

0            10,000
1           500,000
2         5,000,000
3        50,000,000
4           100,000
            ...
10836         5,000
10837           100
10838         1,000
10839         1,000
10840    10,000,000
Name: Installs, Length: 10357, dtype: object

In [116]:
data_copy["Installs"]=data_copy["Installs"].str.replace(",","")   #i want to replace ,

In [117]:
data_copy["Installs"]

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs, Length: 10357, dtype: object

In [119]:
data_copy["Installs"]=data_copy["Installs"].astype("int")

In [120]:
data_copy.head(8)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6,50000,Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19.0,50000,Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29.0,1000000,Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up

In [121]:
data_copy["Price"].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', '$1.20', '$1.04'], dtype=object)

In [124]:
data_copy["Price"]=data_copy["Price"].str.replace("$","")

In [125]:
data_copy["Price"].astype("float")

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
10836    0.0
10837    0.0
10838    0.0
10839    0.0
10840    0.0
Name: Price, Length: 10357, dtype: float64

In [126]:
data_copy["Price"].unique()

array(['0', '4.99', '3.99', '6.99', '1.49', '2.99', '7.99', '5.99',
       '3.49', '1.99', '9.99', '7.49', '0.99', '9.00', '5.49', '10.00',
       '24.99', '11.99', '79.99', '16.99', '14.99', '1.00', '29.99',
       '12.99', '2.49', '10.99', '1.50', '19.99', '15.99', '33.99',
       '74.99', '39.99', '3.95', '4.49', '1.70', '8.99', '2.00', '3.88',
       '25.99', '399.99', '17.99', '400.00', '3.02', '1.76', '4.84',
       '4.77', '1.61', '2.50', '1.59', '6.49', '1.29', '5.00', '13.99',
       '299.99', '379.99', '37.99', '18.99', '389.99', '19.90', '8.49',
       '1.75', '14.00', '4.85', '46.99', '109.99', '154.99', '3.08',
       '2.59', '4.80', '1.96', '19.40', '3.90', '4.59', '15.46', '3.04',
       '4.29', '2.60', '3.28', '4.60', '28.99', '2.95', '2.90', '1.97',
       '200.00', '89.99', '2.56', '30.99', '3.61', '394.99', '1.26',
       '1.20', '1.04'], dtype=object)

In [127]:
data_copy.sample(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10260,Barcelona Wallpaper HD,PERSONALIZATION,4.5,93,5.7,10000,Free,0,Everyone,Personalization,"February 28, 2018",1.10,4.1 and up
7879,I AM C.T.,HEALTH_AND_FITNESS,4.6,28,20.0,1000,Free,0,Mature 17+,Health & Fitness,"April 27, 2017",1.0,4.0.3 and up
1693,Zombie Catchers,GAME,4.7,990491,75.0,10000000,Free,0,Everyone,Action,"May 24, 2018",1.0.27,4.1 and up
880,Girly Lock Screen Wallpaper with Quotes,ENTERTAINMENT,4.2,32458,18.0,5000000,Free,0,Everyone,Entertainment,"June 19, 2018",2.2,4.1 and up
4506,Q Avatar (Avatar Maker),COMICS,4.4,2012,3.6,100000,Free,0,Everyone,Comics,"March 4, 2017",1.3.5,2.3 and up

In [128]:
data_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10357 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10357 non-null  object
 1   Category        10357 non-null  object
 2   Rating          8892 non-null   float64
 3   Reviews         10357 non-null  int64
 4   Size            8831 non-null   float64
 5   Installs        10357 non-null  int64
 6   Type            10356 non-null  object
 7   Price           10357 non-null  object
 8   Content Rating  10357 non-null  object
 9   Genres          10357 non-null  object
 10  Last Updated    10357 non-null  object
 11  Current Ver     10349 non-null  object
 12  Android Ver     10355 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 1.4+ MB

In [129]:
data_copy["Last Updated"]

0         January 7, 2018
1        January 15, 2018
2          August 1, 2018
3            June 8, 2018
4           June 20, 2018
               ...
10836       July 25, 2017
10837        July 6, 2018
10838    January 20, 2017
10839    January 19, 2015
10840       July 25, 2018
Name: Last Updated, Length: 10357, dtype: object

In [130]:
data_copy["Last Updated"]=pd.to_datetime(data_copy["Last Updated"])

In [131]:
data_copy["Last Updated"]

0       2018-01-07
1       2018-01-15
2       2018-08-01
3       2018-06-08
4       2018-06-20
           ...
10836   2017-07-25
10837   2018-07-06
10838   2017-01-20
10839   2015-01-19
10840   2018-07-25
Name: Last Updated, Length: 10357, dtype: datetime64[ns]

In [132]:
data_copy.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up

In [133]:
data_copy["Last Updated"].dt.day   #if you want to extract the day

0         7
1        15
2         1
3         8
4        20
         ..
10836    25
10837     6
10838    20
10839    19
10840    25
Name: Last Updated, Length: 10357, dtype: int32

In [134]:
data_copy["Last Updated"].dt.month

0        1
1        1
2        8
3        6
4        6
        ..
10836    7
10837    7
10838    1
10839    1
10840    7
Name: Last Updated, Length: 10357, dtype: int32

In [135]:
data_copy["Last Updated"].dt.year

0        2018
1        2018
2        2018
3        2018
4        2018
         ...
10836    2017
10837    2018
10838    2017
10839    2015
10840    2018
Name: Last Updated, Length: 10357, dtype: int32

In [136]:
#you can create new column also
data_copy["day"]=data_copy["Last Updated"].dt.day
data_copy["month"]=data_copy["Last Updated"].dt.month
data_copy["year"]=data_copy["Last Updated"].dt.year

In [137]:
data_copy.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

In [141]:
data_copy["Current Ver"]=data_copy["Current Ver"].str.replace("Varies with device",str(np.nan))

In [142]:
data_copy["Current Ver"].isnull().sum()

np.int64(8)

In [143]:
data_copy["Android Ver"]=data_copy["Android Ver"].str.replace("and up","")

In [144]:
data_copy["Android Ver"]

0                    4.0.3
1                    4.0.3
2                    4.0.3
3                      4.2
4                      4.4
                ...
10836                  4.1
10837                  4.1
10838                  2.2
10839    Varies with device
10840    Varies with device
Name: Android Ver, Length: 10357, dtype: object

In [145]:
data_copy.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,,4.2,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4,20,6,2018

In [147]:
data_copy.to_csv("cleaned_google_playstore_data.csv",index=False)