In [1]:
import pandas as pd

In [2]:
data_frame=pd.DataFrame()

In [3]:
data_frame

Empty DataFrame
Columns: []
Index: []

In [4]:
type(data_frame)

pandas.core.frame.DataFrame

i want to create a data frame i can use
list
dict
series
numpy array

In [5]:
data=[1,2,3,4,5]

In [6]:
pd.DataFrame(data)

   0
0  1
1  2
2  3
3  4
4  5

In [7]:
data2=[["monika",19],["aryan",21],["mansi",22]]

In [8]:
data_frame2=pd.DataFrame(data2,columns=["Name","age"],index=["first","second","third"])

In [9]:
data_frame2

          Name  age
first   monika   19
second   aryan   21
third    mansi   22

In [10]:
data3={"Name":["monika","mansi","aryan"], "Age":[19,22,21]}

In [11]:
data_frame3=pd.DataFrame(data3)

In [12]:
data_frame3

     Name  Age
0  monika   19
1   mansi   22
2   aryan   21

In [13]:
data4=[{"col1":19,"col2":21},{"col1":25,"col2":31,"col3":35}]

In [14]:
data_frame4=pd.DataFrame(data4)

In [15]:
data_frame4

   col1  col2  col3
0    19    21   NaN
1    25    31  35.0

In [16]:
data_frame4['col3'].dtype

dtype('float64')

In [17]:
data_frame4['col2'].dtype

dtype('int64')

In [18]:
pd.read_csv("test.csv")

     Name  Age        Designation Salary
0  monika   19     data scientist    15k
1   mansi   22  digital marketing    20k
2   aryan   21        ml engineer    25k

In [19]:
pd.read_csv("test2.tsv")

      Name\tAge\tDesignation\tSalary
0    monika\t19\tdata scientist\t15k
1  mansi\t22\tdigital marketing\t20k
2        aryan\t21\tml engineer\t25k

In [20]:
pd.read_csv("test2.tsv",sep='\t')

     Name  Age        Designation Salary
0  monika   19     data scientist    15k
1   mansi   22  digital marketing    20k
2   aryan   21        ml engineer    25k

In [21]:
pd.read_csv("test3.txt")

      Name@Age@Designation@Salary
0    monika@19@data scientist@15k
1  mansi@22@digital marketing@20k
2        aryan@21@ml engineer@25k

In [22]:
pd.read_csv("test3.txt",sep="@")

     Name  Age        Designation Salary
0  monika   19     data scientist    15k
1   mansi   22  digital marketing    20k
2   aryan   21        ml engineer    25k

In [23]:
data = '''{

  "name": "Monika",
  "age": 22,
  "skills": ["Python", "HTML"],
  "is_student": true 
  
}'''

In [24]:
import json
d=json.loads(data)

In [25]:
d

{'name': 'Monika', 'age': 22, 'skills': ['Python', 'HTML'], 'is_student': True}

In [26]:
type(d)

dict

In [27]:
pd.DataFrame(d)

     name  age  skills  is_student
0  Monika   22  Python        True
1  Monika   22    HTML        True

In [28]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\monika bhati\anaconda3\lib\site-packages (5.2.1)

In [29]:
import sys
print(sys.executable)

C:\Users\monika Bhati\AppData\Local\Programs\Python\Python313\python.exe

In [30]:
data= pd.read_csv("test.csv")

In [31]:
data.shape

(3, 4)

In [32]:
data.dtypes

Name           object
Age             int64
Designation    object
Salary         object
dtype: object

In [33]:
data.head(2)

     Name  Age        Designation Salary
0  monika   19     data scientist    15k
1   mansi   22  digital marketing    20k

In [34]:
data.tail(2)

    Name  Age        Designation Salary
1  mansi   22  digital marketing    20k
2  aryan   21        ml engineer    25k

In [35]:
data.sample(n=3)

     Name  Age        Designation Salary
0  monika   19     data scientist    15k
1   mansi   22  digital marketing    20k
2   aryan   21        ml engineer    25k

In [36]:
data.values

array([['monika', 19, 'data scientist', '15k'],
       ['mansi', 22, 'digital marketing', '20k'],
       ['aryan', 21, 'ml engineer', '25k']], dtype=object)

In [37]:
data.size    #row*column

12

In [38]:
data.ndim   #no. of dimension

2

In [39]:
data.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['Name', 'Age', 'Designation', 'Salary'], dtype='object')]

In [40]:
data.T   #transpose of the data

                          0                  1            2
Name                 monika              mansi        aryan
Age                      19                 22           21
Designation  data scientist  digital marketing  ml engineer
Salary                  15k                20k          25k

In [41]:
data.empty

False

In [42]:
pd.DataFrame().empty

True

apply()   function

In [43]:
import numpy as np

In [44]:
np.random.randn(5,3)

array([[ 1.12784734, -0.15298955, -1.0530472 ],
       [-0.77198654, -0.91592415,  0.01008057],
       [-0.03110365,  0.96138134, -0.92943627],
       [-1.35334498, -0.75356782,  0.60165947],
       [-0.35725661, -0.38782065,  0.75868096]])

In [45]:
pd.DataFrame(np.random.randn(5,3))

          0         1         2
0 -0.911873 -1.306822  0.220037
1  0.656869 -0.247482 -2.459245
2 -1.885559  0.610796  0.674817
3  0.195312  1.378708 -0.707209
4  1.902298  1.952190 -0.105781

In [46]:
dataframe=pd.DataFrame(np.random.randn(5,3),columns=["col1","col2","col3"])

In [47]:
dataframe

       col1      col2      col3
0  0.858986  1.707981 -0.480202
1  1.931986  2.902734  1.495769
2 -0.040271 -0.245904 -0.684517
3 -0.950824  0.840686  1.199643
4 -0.438825  0.320009  1.161900

In [48]:
dataframe.apply(np.mean)

col1    0.272210
col2    1.105101
col3    0.538519
dtype: float64

In [49]:
dataframe.apply(np.median)

col1   -0.040271
col2    0.840686
col3    1.161900
dtype: float64

In [50]:
dataframe.apply(lambda x:x.max())

col1    1.931986
col2    2.902734
col3    1.495769
dtype: float64

In [51]:
dataframe.apply(lambda x:x.min())

col1   -0.950824
col2   -0.245904
col3   -0.684517
dtype: float64

In [52]:
 0.246655-(-0.281506)

0.528161

In [53]:
dataframe.apply(lambda x:x.max()-x.min())

col1    2.882811
col2    3.148637
col3    2.180286
dtype: float64

In [54]:
dataframe["col1"].apply(lambda x:x+100)

0    100.858986
1    101.931986
2     99.959729
3     99.049176
4     99.561175
Name: col1, dtype: float64

map(sequence,func)

In [56]:
df=dataframe["col1"].map(lambda x:x*100)

In [57]:
df

0     85.898572
1    193.198644
2     -4.027105
3    -95.082416
4    -43.882542
Name: col1, dtype: float64

In [58]:
dataframe

       col1      col2      col3
0  0.858986  1.707981 -0.480202
1  1.931986  2.902734  1.495769
2 -0.040271 -0.245904 -0.684517
3 -0.950824  0.840686  1.199643
4 -0.438825  0.320009  1.161900

In [59]:
dataframe.rename(columns={"col1":"c1"})

         c1      col2      col3
0  0.858986  1.707981 -0.480202
1  1.931986  2.902734  1.495769
2 -0.040271 -0.245904 -0.684517
3 -0.950824  0.840686  1.199643
4 -0.438825  0.320009  1.161900

In [60]:
dataframe.rename(columns={"col1":"c1"},index={0:"monika"})

              c1      col2      col3
monika  0.858986  1.707981 -0.480202
1       1.931986  2.902734  1.495769
2      -0.040271 -0.245904 -0.684517
3      -0.950824  0.840686  1.199643
4      -0.438825  0.320009  1.161900

In [61]:
for i in dataframe:
    print(i)

col1
col2
col3

In [64]:
for col,row in dataframe.items():
    print(col,row)

col1 0    0.858986
1    1.931986
2   -0.040271
3   -0.950824
4   -0.438825
Name: col1, dtype: float64
col2 0    1.707981
1    2.902734
2   -0.245904
3    0.840686
4    0.320009
Name: col2, dtype: float64
col3 0   -0.480202
1    1.495769
2   -0.684517
3    1.199643
4    1.161900
Name: col3, dtype: float64

In [66]:
for col,row in dataframe.iterrows():
    print(col,row)

0 col1    0.858986
col2    1.707981
col3   -0.480202
Name: 0, dtype: float64
1 col1    1.931986
col2    2.902734
col3    1.495769
Name: 1, dtype: float64
2 col1   -0.040271
col2   -0.245904
col3   -0.684517
Name: 2, dtype: float64
3 col1   -0.950824
col2    0.840686
col3    1.199643
Name: 3, dtype: float64
4 col1   -0.438825
col2    0.320009
col3    1.161900
Name: 4, dtype: float64

In [67]:
for d in dataframe.itertuples():
    print(d)

Pandas(Index=0, col1=0.8589857154150399, col2=1.707980716133359, col3=-0.4802016141167616)
Pandas(Index=1, col1=1.9319864446140564, col2=2.9027336705462, col3=1.495768913610675)
Pandas(Index=2, col1=-0.04027104501638228, col2=-0.2459037814849118, col3=-0.68451660435889)
Pandas(Index=3, col1=-0.9508241620276701, col2=0.8406864120118731, col3=1.199643358036372)
Pandas(Index=4, col1=-0.4388254185961557, col2=0.3200088974607311, col3=1.1618996000252009)

#sort values
sort_values()

In [72]:
dataframe.sort_values(by='col1')

       col1      col2      col3
3 -0.950824  0.840686  1.199643
4 -0.438825  0.320009  1.161900
2 -0.040271 -0.245904 -0.684517
0  0.858986  1.707981 -0.480202
1  1.931986  2.902734  1.495769

In [70]:
dataframe

       col1      col2      col3
0  0.858986  1.707981 -0.480202
1  1.931986  2.902734  1.495769
2 -0.040271 -0.245904 -0.684517
3 -0.950824  0.840686  1.199643
4 -0.438825  0.320009  1.161900

In [69]:
dataframe.sort_values(by=['col1','col2'])

       col1      col2      col3
3 -0.950824  0.840686  1.199643
4 -0.438825  0.320009  1.161900
2 -0.040271 -0.245904 -0.684517
0  0.858986  1.707981 -0.480202
1  1.931986  2.902734  1.495769

In [11]:
import pandas as pd
import numpy as np
data={
    "energy source":["solar","wind","hydropower","geothermal","blomass","nuclear"],
    "energy consumption(mwh)":[1200,np.nan,2900,np.nan,2500,3200],
    "cost(Millions$)":[200,400,np.nan,150,250,np.nan]
}
energy_df = pd.DataFrame(data)
print("original energy data with missing values:")
energy_df

original energy data with missing values:

  energy source  energy consumption(mwh)  cost(Millions$)
0         solar                   1200.0            200.0
1          wind                      NaN            400.0
2    hydropower                   2900.0              NaN
3    geothermal                      NaN            150.0
4       blomass                   2500.0            250.0
5       nuclear                   3200.0              NaN

In [18]:
energy_df["energy consumption(mwh)"].fillna(energy_df["energy consumption(mwh)"].mean(),inplace=True)
energy_df["cost(Millions$)"].fillna(energy_df["cost(Millions$)"].mean(),inplace=True)
print("\Data after inputing missing value with mean:")
energy_df

\Data after inputing missing value with mean:

<>:3: SyntaxWarning: invalid escape sequence '\D'
<>:3: SyntaxWarning: invalid escape sequence '\D'
C:\Users\monika Bhati\AppData\Local\Temp\ipykernel_1748\1958535054.py:3: SyntaxWarning: invalid escape sequence '\D'
  print("\Data after inputing missing value with mean:")
C:\Users\monika Bhati\AppData\Local\Temp\ipykernel_1748\1958535054.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  energy_df["energy consumption(mwh)"].fillna(energy_df["energy consumption(mwh)"].mean(),inplace=True)
C:\Users\monika Bhati\AppData\Local\Temp\ipykernel_1748\1958535054.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  energy_df["cost(Millions$)"].fillna(energy_df["cost(Millions$)"].mean(),inplace=True)

  energy source  energy consumption(mwh)  cost(Millions$)
0         solar                   1200.0            200.0
1          wind                   2450.0            400.0
2    hydropower                   2900.0            250.0
3    geothermal                   2450.0            150.0
4       blomass                   2500.0            250.0
5       nuclear                   3200.0            250.0

In [8]:
#remove rows with any missing values
#dropna has a parameter axis=1 or 0....0 is bydefault 0 means row
#if i put 1 the whole column will be removed
#it is used mainely when 75% data is nan then we can remove the column

cleaned_df = energy_df.dropna()    

print("original energy data with misssing values:")
cleaned_df

original energy data with misssing values:

  energy source  energy consumption(mwh)  cost(Millions$)
0         solar                   1200.0            200.0
4       blomass                   2500.0            250.0

In [10]:
#removes columns with any NaN values.
cleaned_df = energy_df.dropna(axis=1)    

print("original energy data with misssing values:")
cleaned_df

original energy data with misssing values:

  energy source
0         solar
1          wind
2    hydropower
3    geothermal
4       blomass
5       nuclear

In [ ]:
pip install scikit-learn

In [30]:
from sklearn.preprocessing import MinMaxScaler  

scaler = MinMaxScaler()
energy_df[["energy consumption(mwh)", "cost(Millions$)"]] = scaler.fit_transform(
    energy_df[["energy consumption(mwh)", "cost(Millions$)"]]  
)

print("\nData after normalization (Min-Max Scaling):")
print(energy_df)

Data after normalization (Min-Max Scaling):
  energy source  energy consumption(mwh)  cost(Millions$)
0         solar                    0.000              0.2
1          wind                    0.625              1.0
2    hydropower                    0.850              0.4
3    geothermal                    0.625              0.0
4       blomass                    0.650              0.4
5       nuclear                    1.000              0.4

# Encoding is the process of converting categorical (text) data into numeric form so that machine learning algorithms can understand and work with it.

In [34]:
energy_encoded_df=pd.get_dummies(energy_df,columns=["energy source"])
print("\nData after one-Hot encoding categorical variable:")
energy_encoded_df

Data after one-Hot encoding categorical variable:

,energy consumption(mwh),cost(Millions$),energy source_blomass,energy source_geothermal,energy source_hydropower,energy source_nuclear,energy source_solar,energy source_wind
0,0.000,0.2,False,False,False,False,True,False
1,0.625,1.0,False,False,False,False,False,True
2,0.850,0.4,False,False,True,False,False,False
3,0.625,0.0,False,True,False,False,False,False
4,0.650,0.4,True,False,False,False,False,False
5,1.000,0.4,False,False,False,True,False,False

In [31]:

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import pandas as pd

df = pd.DataFrame({'Gender': ['Male', 'Female', 'Female', 'Male']})

# Label Encoding
label = LabelEncoder()
df['Gender_encoded'] = label.fit_transform(df['Gender'])

print(df)

   Gender  Gender_encoded
0    Male               1
1  Female               0
2  Female               0
3    Male               1