In [4]:
import seaborn 
dataset=seaborn.load_dataset('tips')

In [6]:
dataset

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
dataset['sex'].unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

## Handling missing values(no null value no need to handle it)
## handling categorical features
## handling outiers
## feature scaling
## automating the entire

In [9]:
dataset.shape

(244, 7)

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
encoder=LabelEncoder()

In [13]:
dataset['time']=encoder.fit_transform(dataset['time'])

In [14]:
dataset.head()

   total_bill   tip     sex smoker  day  time  size
0       16.99  1.01  Female     No  Sun     0     2
1       10.34  1.66    Male     No  Sun     0     3
2       21.01  3.50    Male     No  Sun     0     3
3       23.68  3.31    Male     No  Sun     0     2
4       24.59  3.61  Female     No  Sun     0     4

In [15]:
dataset['time'].value_counts()

time
0    176
1     68
Name: count, dtype: int64

In [16]:
# segrate the independent and dependent features
x=dataset.drop(labels=['time'],axis=1)

In [17]:
x.head()

   total_bill   tip     sex smoker  day  size
0       16.99  1.01  Female     No  Sun     2
1       10.34  1.66    Male     No  Sun     3
2       21.01  3.50    Male     No  Sun     3
3       23.68  3.31    Male     No  Sun     2
4       24.59  3.61  Female     No  Sun     4

In [18]:
y=dataset['time']

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [20]:
x_train.head()

     total_bill   tip   sex smoker   day  size
228       13.28  2.72  Male     No   Sat     2
208       24.27  2.03  Male    Yes   Sat     2
96        27.28  4.00  Male    Yes   Fri     2
167       31.71  4.50  Male     No   Sun     4
84        15.98  2.03  Male     No  Thur     2

In [21]:
from sklearn.impute import SimpleImputer  #handling missing values
from sklearn.preprocessing import OneHotEncoder #handling categorical features
from sklearn.preprocessing import StandardScaler #feature scaling
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [22]:
dataset.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [23]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    int64
 6   size        244 non-null    int64
dtypes: category(3), float64(2), int64(2)
memory usage: 8.9 KB

In [24]:
categorical_column=['sex','smoker','day']
numeric_column=['total_bill','tip','size']

In [25]:
dataset[categorical_column]

        sex smoker   day
0    Female     No   Sun
1      Male     No   Sun
2      Male     No   Sun
3      Male     No   Sun
4    Female     No   Sun
..      ...    ...   ...
239    Male     No   Sat
240  Female    Yes   Sat
241    Male    Yes   Sat
242    Male     No   Sat
243  Female     No  Thur

[244 rows x 3 columns]

In [26]:
dataset[numeric_column]

     total_bill   tip  size
0         16.99  1.01     2
1         10.34  1.66     3
2         21.01  3.50     3
3         23.68  3.31     2
4         24.59  3.61     4
..          ...   ...   ...
239       29.03  5.92     3
240       27.18  2.00     2
241       22.67  2.00     2
242       17.82  1.75     2
243       18.78  3.00     2

[244 rows x 3 columns]

# create a pipeline

In [27]:
numeric_pipeline = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy="median")),  #handling missing value
        ('onehotencoder',StandardScaler())  #categorical features to numerical
    ]
)
cat_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy="most_frequent")),  #handling missing value
        ('onehot', OneHotEncoder(handle_unknown='ignore'))  #categorical features to numerical
    ]
)

In [28]:
preprocessor=ColumnTransformer([
    ('numeric_pipeline',numeric_pipeline,numeric_column),
    ('cat_pipeline' , cat_pipeline,categorical_column)
])

In [29]:
x_train=preprocessor.fit_transform(x_train)

In [30]:
x_test=preprocessor.transform(x_test)

In [57]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [32]:
models={
    'Random Forest':RandomForestClassifier(),
    'Decision Tree':DecisionTreeClassifier(),
    'SVC' :SVC()
}

In [43]:
print(list(models.keys())[0])
print(list(models.keys())[1])
print(list(models.keys())[2])

Random Forest
Decision Tree
SVC

In [41]:
list

list

In [70]:
def evaluate_model(x_train,x_test,y_train,y_test,models):
    report={}
    for i in range(len(models)):
        model=list(models.values())[i]
        model.fit(x_train,y_train)

        y_pred=model.predict(x_test)
        acc_score = accuracy_score(y_test,y_pred)
        acc_score=round(acc_score*100,2)
        report[list(models.keys())[i]]=acc_score
    return report

In [71]:
evaluate_model(x_train, x_test, y_train, y_test, models)

{'Random Forest': 95.92, 'Decision Tree': 93.88, 'SVC': 95.92}

In [72]:
classifier=RandomForestClassifier()

In [76]:
params={

    "max_depth":[3,5,8,12],
    "n_estimators":[130,300,600],
    "criterion":["gini","entropy"],
    "max_features":["sqrt","log2"]         
    
}

In [77]:
from sklearn.model_selection import GridSearchCV

In [80]:
hp_model=GridSearchCV(classifier,param_grid=params,scoring='accuracy',cv=5,verbose=3,n_jobs=-1)

In [81]:
hp_model

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 8, 12],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [130, 300, 600]},
             scoring='accuracy', verbose=3)

In [82]:
hp_model.fit(x_train,y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 8, 12],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [130, 300, 600]},
             scoring='accuracy', verbose=3)

In [83]:
hp_model.best_params_

{'criterion': 'gini',
 'max_depth': 12,
 'max_features': 'sqrt',
 'n_estimators': 300}

In [86]:
classifier=RandomForestClassifier(criterion='gini',max_depth=3,max_features='sqrt',n_estimators=100)

In [87]:
classifier.fit(x_train,y_train)

RandomForestClassifier(max_depth=3)

In [90]:
classifier.score(x_train,y_train)

0.958974358974359

In [91]:
y_pred=classifier.predict(x_test)

In [92]:
accuracy_score(y_test,y_pred)

1.0